# JOB SERVICE
spring.cloud.gateway.routes[0].id=job-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/job-service/**

# SEARCH SERVICE
spring.cloud.gateway.routes[1].id=search-service
spring.cloud.gateway.routes[1].uri=http://localhost:8086
spring.cloud.gateway.routes[1].predicates[0]=Path=/search-service/**

# APPLICATION SERVICE
spring.cloud.gateway.routes[2].id=application-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/application-service/**

# USER SERVICE
spring.cloud.gateway.routes[3].id=user-service
spring.cloud.gateway.routes[3].uri=http://localhost:8081
spring.cloud.gateway.routes[3].predicates[0]=Path=/user-service/**

# RESUME SERVICE
spring.cloud.gateway.routes[4].id=resume-service
spring.cloud.gateway.routes[4].uri=http://localhost:8084
spring.cloud.gateway.routes[4].predicates[0]=Path=/resume-service/**