
# SERVER CONFIG

server.port=8081
spring.application.name=user-service


# DATABASE CONFIG (PostgreSQL)

spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal_user_db
spring.datasource.username=postgres
spring.datasource.password=1424

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# LOGGING

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# SECURITY (BASIC - TEMP)

spring.security.user.name=admin
spring.security.user.password=admin


# JACKSON (OPTIONAL)

spring.jackson.serialization.fail-on-empty-beans=false

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=3600000

server.address=127.0.0.1